class StockLogos {
  /// Local bundled PNG assets (instant offline load, 0ms network latency)
  static const Map<String, String> localAssets = {
    'AARTIIND': 'assets/logos/aartiind.png',
    'ABB': 'assets/logos/abb.png',
    'ABBOTINDIA': 'assets/logos/abbotindia.png',
    'ABCAPITAL': 'assets/logos/abcapital.png',
    'ABFRL': 'assets/logos/abfrl.png',
    'ACC': 'assets/logos/acc.png',
    'ADANIPOWER': 'assets/logos/adanipower.png',
    'ALKEM': 'assets/logos/alkem.png',
    'AMBUJACEM': 'assets/logos/ambujacem.png',
    'APOLLOHOSP': 'assets/logos/apollohosp.png',
    'ASIANPAINT': 'assets/logos/asianpaint.png',
    'ASTRAL': 'assets/logos/astral.png',
    'ATUL': 'assets/logos/atul.png',
    'AUBANK': 'assets/logos/aubank.png',
    'AUROPHARMA': 'assets/logos/auropharma.png',
    'AXISBANK': 'assets/logos/axisbank.png',
    'BAJAJFINSV': 'assets/logos/bajajfinsv.png',
    'BAJFINANCE': 'assets/logos/bajfinance.png',
    'BALKRISIND': 'assets/logos/balkrisind.png',
    'BALRAMCHIN': 'assets/logos/balramchin.png',
    'BANDHANBNK': 'assets/logos/bandhanbnk.png',
    'BANKBARODA': 'assets/logos/bankbaroda.png',
    'BANKNIFTY': 'assets/logos/banknifty.png',
    'BATAINDIA': 'assets/logos/bataindia.png',
    'BEL': 'assets/logos/bel.png',
    'BHEL': 'assets/logos/bhel.png',
    'BIOCON': 'assets/logos/biocon.png',
    'BOSCHLTD': 'assets/logos/boschltd.png',
    'CANBK': 'assets/logos/canbk.png',
    'CANFINHOME': 'assets/logos/canfinhome.png',
    'CHAMBLFERT': 'assets/logos/chamblfert.png',
    'CHOLAFIN': 'assets/logos/cholafin.png',
    'CIPLA': 'assets/logos/cipla.png',
    'COALINDIA': 'assets/logos/coalindia.png',
    'COCHINSHIP': 'assets/logos/cochinship.png',
    'COFORGE': 'assets/logos/coforge.png',
    'CONCOR': 'assets/logos/concor.png',
    'COROMANDEL': 'assets/logos/coromandel.png',
    'CROMPTON': 'assets/logos/crompton.png',
    'CUMMINSIND': 'assets/logos/cumminsind.png',
    'DEEPAKNTR': 'assets/logos/deepakntr.png',
    'DELHIVERY': 'assets/logos/delhivery.png',
    'DLF': 'assets/logos/dlf.png',
    'EICHERMOT': 'assets/logos/eichermot.png',
    'ESCORTS': 'assets/logos/escorts.png',
    'EXIDEIND': 'assets/logos/exideind.png',
    'FEDERALBNK': 'assets/logos/federalbnk.png',
    'GLENMARK': 'assets/logos/glenmark.png',
    'GNFC': 'assets/logos/gnfc.png',
    'GODREJCP': 'assets/logos/godrejcp.png',
    'GODREJPROP': 'assets/logos/godrejprop.png',
    'GRANULES': 'assets/logos/granules.png',
    'HAL': 'assets/logos/hal.png',
    'HAVELLS': 'assets/logos/havells.png',
    'HCLTECH': 'assets/logos/hcltech.png',
    'HDFCBANK': 'assets/logos/hdfcbank.png',
    'HEROMOTOCO': 'assets/logos/heromotoco.png',
    'HINDCOPPER': 'assets/logos/hindcopper.png',
    'HINDPETRO': 'assets/logos/hindpetro.png',
    'ICICIBANK': 'assets/logos/icicibank.png',
    'IDFC': 'assets/logos/idfc.png',
    'IDFCFIRSTB': 'assets/logos/idfcfirstb.png',
    'INDIACEM': 'assets/logos/indiacem.png',
    'INDIAMART': 'assets/logos/indiamart.png',
    'INDIGO': 'assets/logos/indigo.png',
    'INDUSINDBK': 'assets/logos/indusindbk.png',
    'INFY': 'assets/logos/infy.png',
    'IOC': 'assets/logos/ioc.png',
    'IPCALAB': 'assets/logos/ipcalab.png',
    'IRCTC': 'assets/logos/irctc.png',
    'IRFC': 'assets/logos/irfc.png',
    'ITC': 'assets/logos/itc.png',
    'JINDALSTEL': 'assets/logos/jindalstel.png',
    'JKCEMENT': 'assets/logos/jkcement.png',
    'JSL': 'assets/logos/jsl.png',
    'JUBLFOOD': 'assets/logos/jublfood.png',
    'KEI': 'assets/logos/kei.png',
    'KOTAKBANK': 'assets/logos/kotakbank.png',
    'LALPATHLAB': 'assets/logos/lalpathlab.png',
    'LICHSGFIN': 'assets/logos/lichsgfin.png',
    'LT': 'assets/logos/lt.png',
    'LUPIN': 'assets/logos/lupin.png',
    'M&M': 'assets/logos/m&m.png',
    'MANAPPURAM': 'assets/logos/manappuram.png',
    'MARICO': 'assets/logos/marico.png',
    'MARUTI': 'assets/logos/maruti.png',
    'MCX': 'assets/logos/mcx.png',
    'METROPOLIS': 'assets/logos/metropolis.png',
    'MFSL': 'assets/logos/mfsl.png',
    'MGL': 'assets/logos/mgl.png',
    'MOTILALOFS': 'assets/logos/motilalofs.png',
    'MPHASIS': 'assets/logos/mphasis.png',
    'MRF': 'assets/logos/mrf.png',
    'MRPL': 'assets/logos/mrpl.png',
    'MUTHOOTFIN': 'assets/logos/muthootfin.png',
    'NATIONALUM': 'assets/logos/nationalum.png',
    'NAVINFLUOR': 'assets/logos/navinfluor.png',
    'NIFTY50': 'assets/logos/nifty50.png',
    'NLCINDIA': 'assets/logos/nlcindia.png',
    'NMDC': 'assets/logos/nmdc.png',
    'NOCIL': 'assets/logos/nocil.png',
    'NTPC': 'assets/logos/ntpc.png',
    'OBEROIRLTY': 'assets/logos/oberoirlty.png',
    'OFSS': 'assets/logos/ofss.png',
    'PAGEIND': 'assets/logos/pageind.png',
    'PATANJALI': 'assets/logos/patanjali.png',
    'PEL': 'assets/logos/pel.png',
    'PERSISTENT': 'assets/logos/persistent.png',
    'PETRONET': 'assets/logos/petronet.png',
    'PFC': 'assets/logos/pfc.png',
    'PIDILITIND': 'assets/logos/pidilitind.png',
    'PIIND': 'assets/logos/piind.png',
    'PNB': 'assets/logos/pnb.png',
    'POLYCAB': 'assets/logos/polycab.png',
    'PVRINOX': 'assets/logos/pvrinox.png',
    'RAMCOCEM': 'assets/logos/ramcocem.png',
    'RBLBANK': 'assets/logos/rblbank.png',
    'RECLTD': 'assets/logos/recltd.png',
    'RELIANCE': 'assets/logos/reliance.png',
    'RVNL': 'assets/logos/rvnl.png',
    'SAIL': 'assets/logos/sail.png',
    'SBILIFE': 'assets/logos/sbilife.png',
    'SJVN': 'assets/logos/sjvn.png',
    'SRF': 'assets/logos/srf.png',
    'SUPREMEIND': 'assets/logos/supremeind.png',
    'SYNGENE': 'assets/logos/syngene.png',
    'TATASTEEL': 'assets/logos/tatasteel.png',
    'TCS': 'assets/logos/tcs.png',
    'TRENT': 'assets/logos/trent.png',
    'TVSMOTOR': 'assets/logos/tvsmotor.png',
    'UBL': 'assets/logos/ubl.png',
    'ULTRACEMCO': 'assets/logos/ultracemco.png',
    'UNITDSPR': 'assets/logos/unitdspr.png',
  };

  /// Official TradingView logoid mappings for all Indian stocks and indices
  static const Map<String, String> tradingViewLogos = {
    'AARTIIND': 'aarti-industries',
    'ABB': 'abb',
    'ABBOTINDIA': 'abbott',
    'ABCAPITAL': 'aditya-birla-capital',
    'ABFRL': 'aditya-birla-fash',
    'ACC': 'acc',
    'ADANIENT': 'adani',
    'ADANIPORTS': 'adani',
    'ADANIPOWER': 'adani',
    'ALKEM': 'alkem',
    'AMBUJACEM': 'ambuja-cements',
    'APOLLOHOSP': 'apollo-hospitals',
    'ASIANPAINT': 'asian-paints',
    'ASTRAL': 'astral-poly-techni',
    'ATUL': 'atul',
    'AUBANK': 'au-small-finance-b',
    'AUROPHARMA': 'aurobindo',
    'AXISBANK': 'axis-bank',
    'BAJAJFINSV': 'bajaj-finserv-mutual-fund',
    'BAJFINANCE': 'bajaj-finance',
    'BALKRISIND': 'balkrishna',
    'BALRAMCHIN': 'balrampur-chini-mills',
    'BANDHANBNK': 'bandhan-bank',
    'BANKBARODA': 'bank-of-baroda',
    'BANKNIFTY': 'indices/nifty-bank-index',
    'BATAINDIA': 'bata',
    'BEL': 'bharat-electronics',
    'BHEL': 'bharat-heavy-electricals',
    'BIOCON': 'biocon',
    'BOSCHLTD': 'bosch',
    'BPCL': 'bharat-petroleum',
    'BRITANNIA': 'britannia',
    'CANBK': 'canara-bank',
    'CANFINHOME': 'can-fin-homes',
    'CHAMBLFERT': 'chambal-fertilisers-and-chemical',
    'CHOLAFIN': 'cholamandalam',
    'CIPLA': 'cipla',
    'COALINDIA': 'coal-india',
    'COCHINSHIP': 'cochin-shipyard-limited',
    'COFORGE': 'coforge-limited',
    'CONCOR': 'container',
    'COROMANDEL': 'coromandel-international',
    'CROMPTON': 'crompton-greaves-consumer-elec',
    'CUMMINSIND': 'cummins',
    'DEEPAKNTR': 'deepak-nitrite',
    'DELHIVERY': 'delhivery-limited',
    'DIVISLAB': 'divis',
    'DLF': 'dlf',
    'DRREDDY': 'dr-reddys',
    'EICHERMOT': 'eicher-motors',
    'ESCORTS': 'escorts',
    'EXIDEIND': 'exide',
    'FEDERALBNK': 'fed-bank',
    'FINNIFTY': 'indices/nifty-financial-services-index',
    'GLENMARK': 'glenmark',
    'GMRINFRA': 'gmr',
    'GNFC': 'gujarat-narmada-valley-fertilizers-and-chemicals',
    'GODREJCP': 'godrej',
    'GODREJPROP': 'godrej-properties',
    'GRANULES': 'granules',
    'GRASIM': 'grasim',
    'GUJGASLTD': 'gujarat-gas',
    'HAL': 'hindustan-aeronautics-limited',
    'HAVELLS': 'havells',
    'HCLTECH': 'hcl-technologies',
    'HDFCAMC': 'hdfc',
    'HDFCBANK': 'hdfc-bank',
    'HDFCLIFE': 'hdfc-life',
    'HEROMOTOCO': 'hero-motocorp',
    'HINDALCO': 'hindalco',
    'HINDCOPPER': 'hindustan-copper',
    'HINDPETRO': 'hindustan-petroleum',
    'HINDUNILVR': 'unilever',
    'ICICIBANK': 'icici-bank',
    'IDFC': 'idfc-first-bank',
    'IDFCFIRSTB': 'idfc-first-bank',
    'INDIACEM': 'india-cements',
    'INDIAMART': 'indiamart',
    'INDIGO': 'interglobe-aviatio',
    'INDUSINDBK': 'indusind-bank',
    'INFY': 'infosys',
    'IOC': 'indian-oil',
    'IPCALAB': 'ipca',
    'IRCTC': 'indian-rail-tour-corp-ltd',
    'IRFC': 'indian-railway-finance-corporation',
    'ITC': 'itc',
    'JINDALSTEL': 'jindal',
    'JKCEMENT': 'jk-cements',
    'JSL': 'jindal-stainless',
    'JSWSTEEL': 'jsw',
    'JUBLFOOD': 'jubilant-foodworks',
    'KEI': 'kei-industries',
    'KOTAKBANK': 'kotak-mahindra-ast',
    'LALPATHLAB': 'dr-lal-pathlabs',
    'LICHSGFIN': 'lic-housing',
    'LT': 'larsen-and-toubro',
    'LUPIN': 'lupin',
    'M&M': 'mahindra',
    'M&MFIN': 'mahindra-finance',
    'MANAPPURAM': 'manappuram-finance',
    'MARICO': 'marico',
    'MARUTI': 'maruti-suzuki-india',
    'MCX': 'multi-commodity-exchange-of-india-limited',
    'METROPOLIS': 'metropolis-healthcare',
    'MFSL': 'max-financial',
    'MGL': 'mahanagar-gas',
    'MIDCAPNIFTY': 'indices/finnifty',
    'MOTILALOFS': 'motilal',
    'MPHASIS': 'mphasis',
    'MRF': 'mrf',
    'MRPL': 'mangalore-ref-and-pet',
    'MUTHOOTFIN': 'muthoot-finance',
    'NATIONALUM': 'national-aluminum',
    'NAVINFLUOR': 'navin-fluorine-international-l',
    'NESTLEIND': 'nestle',
    'NIFTY50': 'indices/nifty-50',
    'NIFTYAUTO': 'indices/nifty-50',
    'NIFTYENERGY': 'indices/nifty-energy-index',
    'NIFTYFMCG': 'indices/nifty-noncyc-cons',
    'NIFTYINFRA': 'indices/nifty-multi-infra',
    'NIFTYIT': 'indices/nifty-it-index',
    'NIFTYMEDIA': 'indices/nifty-media-index',
    'NIFTYMETAL': 'indices/nifty-metal-index',
    'NIFTYPHARMA': 'indices/nifty-pharma-index',
    'NIFTYPSE': 'indices/nifty-sme-emerge',
    'NIFTYREALTY': 'indices/nifty-housing',
    'NLCINDIA': 'nlc-india',
    'NMDC': 'nmdc',
    'NOCIL': 'nocil',
    'NTPC': 'ntpc',
    'OBEROIRLTY': 'oberoi-realty',
    'OFSS': 'oracle',
    'ONGC': 'oil-and-natural-gas',
    'PAGEIND': 'page-industries',
    'PATANJALI': 'ruchi-soya-industries',
    'PEL': 'pelatro-ltd',
    'PERSISTENT': 'persistent-systems-ltd',
    'PETRONET': 'petronet-lng',
    'PFC': 'power-finance',
    'PIDILITIND': 'pidilite',
    'PIIND': 'pi-industries',
    'PNB': 'punjab-natl-bank',
    'POLYCAB': 'polycab',
    'POWERGRID': 'power-grid',
    'PVRINOX': 'pvr',
    'RAMCOCEM': 'ramco-cements',
    'RBLBANK': 'rbl-bank',
    'RECLTD': 'rec',
    'RELIANCE': 'reliance-industrial-infrastructure',
    'RVNL': 'rail-vikas-nigam',
    'SAIL': 'steel-authority-of-india',
    'SBILIFE': 'sbi-life-insurance',
    'SBIN': 'state-bank',
    'SENSEX': 'indices/bse-sensex',
    'SHRIRAMFIN': 'shriram',
    'SJVN': 'sjvn',
    'SRF': 'srf',
    'SUNPHARMA': 'sun-pharmaceutical',
    'SUPREMEIND': 'supreme-industries',
    'SYNGENE': 'syngene',
    'TATACHEM': 'tata',
    'TATACOMM': 'tata',
    'TATACONSUM': 'tata',
    'TATAPOWER': 'tata',
    'TATASTEEL': 'tata',
    'TCS': 'tata',
    'TECHM': 'mahindra-tech',
    'TRENT': 'trent',
    'TVSMOTOR': 'tvs',
    'UBL': 'united-breweries',
    'ULTRACEMCO': 'ultratech-cement',
    'UNITDSPR': 'united-spirits',
    'VOLTAS': 'voltas',
    'WHIRLPOOL': 'whirlpool',
    'YESBANK': 'yes-bank',
    'ZEEL': 'zee-entertain',
    'ZYDUSLIFE': 'cadila-healthcare',
  };

  /// Returns direct high-resolution vector SVG logo URL from TradingView CDN
  static String getTradingViewLogoUrl(String symbol) {
    final clean = cleanSymbol(symbol);
    final logoid = tradingViewLogos[clean];
    if (logoid != null && logoid.isNotEmpty) {
      return 'https://s3-symbol-logo.tradingview.com/$logoid.svg';
    }
    return '';
  }

  /// Official corporate domains for Nifty 50 + F&O stocks + indices
  /// Used for Google Favicons (primary PNG) and Clearbit (fallback)
  static const Map<String, String> domains = {
    // ── Indices ──────────────────────────────────────────────────────────────
    'NIFTY50':      'nseindia.com',
    'BANKNIFTY':    'nseindia.com',
    'FINNIFTY':     'nseindia.com',
    'MIDCAPNIFTY':  'nseindia.com',
    'SENSEX':       'bseindia.com',
    'NIFTYIT':      'nseindia.com',
    'NIFTYAUTO':    'nseindia.com',
    'NIFTYMETAL':   'nseindia.com',
    'NIFTYPHARMA':  'nseindia.com',
    'NIFTYFMCG':    'nseindia.com',
    'NIFTYINFRA':   'nseindia.com',
    'NIFTYENERGY':  'nseindia.com',
    'NIFTYMEDIA':   'nseindia.com',
    'NIFTYREALTY':  'nseindia.com',
    'NIFTYPSE':     'nseindia.com',

    // ── Nifty 50 ──────────────────────────────────────────────────────────────
    'ADANIENT':     'adani.com',
    'ADANIPORTS':   'adaniports.com',
    'APOLLOHOSP':   'apollohospitals.com',
    'ASIANPAINT':   'asianpaints.com',
    'AXISBANK':     'axisbank.com',
    'BAJAJ-AUTO':   'bajajauto.com',
    'BAJFINANCE':   'bajajfinserv.in',
    'BAJAJFINSV':   'bajajfinserv.in',
    'BPCL':         'bharatpetroleum.com',
    'BHARTIARTL':   'airtel.in',
    'BRITANNIA':    'britannia.co.in',
    'CIPLA':        'cipla.com',
    'COALINDIA':    'coalindia.in',
    'DIVISLAB':     'divislabs.com',
    'DRREDDY':      'drreddys.com',
    'EICHERMOT':    'eichermotors.com',
    'GRASIM':       'grasim.com',
    'HCLTECH':      'hcltech.com',
    'HDFCBANK':     'hdfcbank.com',
    'HDFCLIFE':     'hdfclife.com',
    'HEROMOTOCO':   'heromotocorp.com',
    'HINDALCO':     'hindalco.com',
    'HINDUNILVR':   'hul.co.in',
    'ICICIBANK':    'icicibank.com',
    'ITC':          'itcportal.com',
    'INDUSINDBK':   'indusind.com',
    'INFY':         'infosys.com',
    'JSWSTEEL':     'jsw.in',
    'KOTAKBANK':    'kotak.com',
    'LTIM':         'ltimindtree.com',
    'LT':           'larsentoubro.com',
    'M&M':          'mahindra.com',
    'MARUTI':       'marutisuzuki.com',
    'NTPC':         'ntpc.co.in',
    'NESTLEIND':    'nestle.in',
    'ONGC':         'ongcindia.com',
    'POWERGRID':    'powergridindia.com',
    'RELIANCE':     'ril.com',
    'SBILIFE':      'sbilife.co.in',
    'SBIN':         'sbi.co.in',
    'SHRIRAMFIN':   'shriramfinance.in',
    'SUNPHARMA':    'sunpharma.com',
    'TCS':          'tcs.com',
    'TATACONSUM':   'tataconsumerproducts.com',
    'TATAMOTORS':   'tatamotors.com',
    'TATASTEEL':    'tatasteel.com',
    'TECHM':        'techmahindra.com',
    'TITAN':        'titan.co.in',
    'ULTRACEMCO':   'ultratechcement.com',
    'WIPRO':        'wipro.com',

    // ── F&O / Midcap Stocks ───────────────────────────────────────────────────
    'AARTIIND':     'aartiindustries.com',
    'ABB':          'abb.com',
    'ABBOTINDIA':   'abbott.co.in',
    'ABCAPITAL':    'adityabirlacapital.com',
    'ABFRL':        'adityabirlaonline.com',
    'ACC':          'acclimited.com',
    'ADANIPOWER':   'adanipower.com',
    'ALKEM':        'alkemlabs.com',
    'AMBUJACEM':    'ambujacement.com',
    'ASTRAL':       'astralpipes.com',
    'ATUL':         'atulltd.com',
    'AUBANK':       'aubank.in',
    'AUROPHARMA':   'aurobindo.com',
    'BALKRISIND':   'bkt-tires.com',
    'BALRAMCHIN':   'balrampurchini.com',
    'BANDHANBNK':   'bandhanbank.com',
    'BANKBARODA':   'bankofbaroda.in',
    'BATAINDIA':    'bata.in',
    'BEL':          'bel-india.in',
    'BHEL':         'bhel.com',
    'BIOCON':       'biocon.com',
    'BOSCHLTD':     'bosch.in',
    'CANBK':        'canarabank.in',
    'CANFINHOME':   'canfinhomes.com',
    'CHAMBLFERT':   'chambalfertilisers.com',
    'CHOLAFIN':     'cholamandalam.com',
    'COCHINSHIP':   'cochinshipyard.com',
    'COFORGE':      'coforge.com',
    'CONCOR':       'concorindia.com',
    'COROMANDEL':   'coromandel.farm',
    'CROMPTON':     'crompton.co.in',
    'CUMMINSIND':   'cummins.in',
    'DLF':          'dlf.in',
    'DEEPAKNTR':    'deepaknitrite.com',
    'DELHIVERY':    'delhivery.com',
    'ESCORTS':      'escortskubota.com',
    'EXIDEIND':     'exideindustries.com',
    'FEDERALBNK':   'federalbank.co.in',
    'GLENMARK':     'glenmarkpharma.com',
    'GMRINFRA':     'gmrgroup.in',
    'GNFC':         'gnfc.in',
    'GODREJCP':     'godrejcp.com',
    'GODREJPROP':   'godrejproperties.com',
    'GRANULES':     'granulesindia.com',
    'GUJGASLTD':    'gujaratgas.com',
    'HAL':          'hal-india.co.in',
    'HAVELLS':      'havells.com',
    'HDFCAMC':      'hdfcfund.com',
    'HINDCOPPER':   'hindustancopper.com',
    'HINDPETRO':    'hindustanpetroleum.com',
    'IPCALAB':      'ipca.com',
    'IDFC':         'idfcfirstbank.com',
    'IDFCFIRSTB':   'idfcfirstbank.com',
    'INDIACEM':     'indiacements.com',
    'INDIAMART':    'indiamart.com',
    'INDIGO':       'goindigo.in',
    'IOC':          'iocl.com',
    'IRCTC':        'irctc.co.in',
    'IRFC':         'irfc.nic.in',
    'JINDALSTEL':   'jindalsteelpower.com',
    'JKCEMENT':     'jkcement.com',
    'JSL':          'jindalstainless.com',
    'JUBLFOOD':     'jubilantfoodworks.com',
    'KEI':          'kei-ind.com',
    'L&TFH':        'ltfs.com',
    'LALPATHLAB':   'lalpathlabs.com',
    'LICHSGFIN':    'lichousing.com',
    'LUPIN':        'lupin.com',
    'MRF':          'mrftyres.com',
    'M&MFIN':       'mahindrafinance.com',
    'MANAPPURAM':   'manappuram.com',
    'MARICO':       'marico.com',
    'MCX':          'mcxindia.com',
    'METROPOLIS':   'metropolisindia.com',
    'MFSL':         'maxlifeinsurance.com',
    'MGL':          'mahanagargas.com',
    'MOTILALOFS':   'motilaloswal.com',
    'MPHASIS':      'mphasis.com',
    'MRPL':         'mrpl.co.in',
    'MUTHOOTFIN':   'muthootfinance.com',
    'NATIONALUM':   'nalcoindia.com',
    'NAVINFLUOR':   'navinfluorine.com',
    'NLCINDIA':     'nlcindia.gov.in',
    'NMDC':         'nmdc.co.in',
    'NOCIL':        'nocil.com',
    'OBEROIRLTY':   'oberoirealty.com',
    'OFSS':         'oracle.com',
    'PAGEIND':      'jockeyindia.com',
    'PATANJALI':    'patanjalifoods.com',
    'PEL':          'piramal.com',
    'PERSISTENT':   'persistent.com',
    'PETRONET':     'petronetlng.com',
    'PFC':          'pfcindia.com',
    'PIDILITIND':   'pidilite.com',
    'PIIND':        'piindustries.com',
    'PNB':          'pnbindia.in',
    'POLYCAB':      'polycab.com',
    'PVRINOX':      'pvrinox.com',
    'RAMCOCEM':     'ramcocements.com',
    'RBLBANK':      'rblbank.com',
    'RECLTD':       'recindia.nic.in',
    'RVNL':         'rvnl.org',
    'SAIL':         'sail.co.in',
    'SJVN':         'sjvn.nic.in',
    'SRF':          'srfindia.com',
    'SUPREMEIND':   'supreme.co.in',
    'SYNGENE':      'syngeneintl.com',
    'TATACOMM':     'tatacomm.com',
    'TATAELXSI':    'tataelxsi.com',
    'TATACHEM':     'tatachemicals.com',
    'TATAPOWER':    'tatapower.com',
    'TRENT':        'trentlimited.com',
    'TVSMOTOR':     'tvsmotor.com',
    'UBL':          'unitedbreweries.com',
    'UNITDSPR':     'diageoindia.com',
    'VOLTAS':       'voltas.com',
    'WHIRLPOOL':    'whirlpoolindia.com',
    'YESBANK':      'yesbank.in',
    'ZEEL':         'zee.com',
    'ZYDUSLIFE':    'zyduslife.com',
  };

  /// Cleans symbols by stripping index suffixes, mapping aliases.
  static String cleanSymbol(String symbol) {
    var clean = symbol.toUpperCase().trim();
    if (clean == '^NSEI' || clean == 'NSEI') return 'NIFTY50';
    if (clean == '^NSEBANK' || clean == 'NSEBANK') return 'BANKNIFTY';
    if (clean.startsWith('^')) {
      clean = clean.substring(1);
    }
    if (clean.contains('.')) {
      clean = clean.split('.').first;
    }
    return clean;
  }

  /// Primary logo URL — TradingView vector SVG, Google Favicon, or Clearbit
  static String getLogoUrl(String symbol) {
    final clean = cleanSymbol(symbol);
    final tvUrl = getTradingViewLogoUrl(clean);
    if (tvUrl.isNotEmpty) return tvUrl;
    
    final domain = domains[clean];
    if (domain == null) return '';
    return 'https://www.google.com/s2/favicons?domain=$domain&sz=128';
  }

  /// Fallback logo URL using Google Favicons
  static String getFallbackLogoUrl(String symbol) {
    final clean = cleanSymbol(symbol);
    final domain = domains[clean];
    if (domain == null) return '';
    return 'https://www.google.com/s2/favicons?domain=$domain&sz=128';
  }

  /// Returns true if a logo source exists for this symbol
  static bool hasLogo(String symbol) {
    final clean = cleanSymbol(symbol);
    return localAssets.containsKey(clean) || tradingViewLogos.containsKey(clean) || domains.containsKey(clean);
  }
}
