// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return web;
      case TargetPlatform.linux:
        return web;
      default:
        return web;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1_n0v8ug6tRgAOJCGtZL81QaURyaM7GE',
    appId: '1:863653253432:web:b1c73526b6f7d40adef1cd',
    messagingSenderId: '863653253432',
    projectId: 'mst7-3fb55',
    authDomain: 'mst7-3fb55.firebaseapp.com',
    databaseURL: 'https://mst7-3fb55-default-rtdb.firebaseio.com',
    storageBucket: 'mst7-3fb55.firebasestorage.app',
    measurementId: 'G-S04EQL2ZLN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1_n0v8ug6tRgAOJCGtZL81QaURyaM7GE',
    appId: '1:863653253432:android:99913e8bb89e8cb9def1cd',
    messagingSenderId: '863653253432',
    projectId: 'mst7-3fb55',
    databaseURL: 'https://mst7-3fb55-default-rtdb.firebaseio.com',
    storageBucket: 'mst7-3fb55.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1_n0v8ug6tRgAOJCGtZL81QaURyaM7GE',
    appId: '1:863653253432:ios:742e97e88b8849badef1cd',
    messagingSenderId: '863653253432',
    projectId: 'mst7-3fb55',
    databaseURL: 'https://mst7-3fb55-default-rtdb.firebaseio.com',
    storageBucket: 'mst7-3fb55.firebasestorage.app',
    iosBundleId: 'com.bigshot.orderflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1_n0v8ug6tRgAOJCGtZL81QaURyaM7GE',
    appId: '1:863653253432:ios:742e97e88b8849badef1cd',
    messagingSenderId: '863653253432',
    projectId: 'mst7-3fb55',
    databaseURL: 'https://mst7-3fb55-default-rtdb.firebaseio.com',
    storageBucket: 'mst7-3fb55.firebasestorage.app',
    iosBundleId: 'com.bigshot.orderflow',
  );
}
