org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -XX:CICompilerCount=2 -XX:ParallelGCThreads=2 -XX:ConcGCThreads=2 -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.workers.max=1
org.gradle.daemon.idletimeout=60000
android.useAndroidX=true
android.enableJetifier=true
